### PR TITLE
XBox: Fix align_val_t in include/new

### LINKED ISSUE #587: error: no type named 'align_val_t' in namespace 'std'
```
/opt/nxdk/lib/libcxx/include/new:205:102: error: no type named 'align_val_t' in namespace 'std'
_LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new(std::size_t __sz, std::align_val_t) _THROW_BAD_ALLOC;
```

### PR DESCRIPTION
**Pull request by glebm**
Fixes https://github.com/XboxDev/nxdk/issues/587

### CODE REVIEW

**Comment by glebm** [comment]
This only fixes the declarations but there is nothing to actually link them against.

The built-in C++ aligned allocation is not defined:

```
lld: error: undefined symbol: void * __cdecl operator new(unsigned int, enum std::align_val_t)
```

Neither are `_aligned_malloc` and `posix_memalloc`.

**Comment by glebm** [comment]
Updated the patch.

It now works together with https://github.com/XboxDev/nxdk-pdclib/pull/52 and https://github.com/XboxDev/nxdk/pull/603 :tada:

**Comment by glebm** [comment]
@Ryzee119 This needs to be merged as well to fully enable aligned_alloc (and submodule needs to be bumped in nxdk)

**Comment by thrimbor** [comment]
Appears to work fine, merging

**Pull request merged**
